[package]
name = "chip8"
version = "0.1.0"
authors = ["mstelmas"]

[dependencies]
log = "0.4"
env_logger = "0.5.10"
sdl2 = "0.31.0"
rand = "0.3.15"

[[bin]]
name = "debugger"
path = "src/debugger/main.rs"

[[bin]]
name = "chip8"
path = "src/chip8vm/main.rs"